### ISSUE TITLE
Train and Predict recipes: support for k8s and remote filesystems

### ISSUE THREAD

**Issue by alexcombessie** [dataiku/dss-plugin-timeseries-forecast-legacy#7]

**Comment by ElianoMarques** [comment]
Thanks for this. I think the challenge is more related to ensuring saving is performed when running the plugin in a container. For some reason its showing an error as it cant find the path for file system.

**Comment by alexcombessie** [comment]
You can use these functions:
- dkuManagedFolderCopyFromLocal
- dkuManagedFolderCopyToLocal
on your cwd()
from https://doc.dataiku.com/dss/api/5.1/R/dataiku/reference/index.html

to edit SaveForecastingObjects and LoadForecastingObjects

**Comment by alexcombessie** [comment]
Closed with #15
